# Generated by Django 5.2.9 on 2025-12-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='passengers_details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
